Assignment4
meta-nilesh-patel/GET2020 pull request #5
Opened 2020-01-17 17:47 UTC by meta-nilesh-patel

Only check assignment 4!

2020-01-27 05:26 UTC, rash-tiwari commented on SCF/Assignment4/ArrOperation.java
> +
Correct the formatting for this method

2020-01-27 05:27 UTC, rash-tiwari commented on SCF/Assignment4/TestMethodFixXYInArray.java
> +			this.inputArray = input;
Remove extra tab from here.

2020-01-27 05:28 UTC, rash-tiwari commented on SCF/Assignment4/TestMethodGetSplitIndexInArray.java
> +			this.inputArray = input;
remove unnecessary tab

2020-01-27 05:28 UTC, rash-tiwari commented on SCF/Assignment4/ArrOperation.java
> +		}else
Add else in new line

2020-01-27 07:17 UTC, rash-tiwari requested changes
1st Level Code Review Done

2020-01-27 09:14 UTC, meta-nilesh-patel commented on SCF/Assignment4/ArrOperation.java
> +
Done

2020-01-27 09:20 UTC, meta-nilesh-patel commented on SCF/Assignment4/TestMethodFixXYInArray.java
> +			this.inputArray = input;
Done

2020-01-27 09:20 UTC, meta-nilesh-patel commented on SCF/Assignment4/TestMethodGetSplitIndexInArray.java
> +			this.inputArray = input;
Done

2020-01-27 09:20 UTC, meta-nilesh-patel commented on SCF/Assignment4/ArrOperation.java
> +		}else
Done

2020-02-13 09:34 UTC, rash-tiwari approved these changes

2020-02-13 09:34 UTC, merged