SCF/Assignment6
meta-nilesh-patel/GET2020 pull request #7
Opened 2020-01-21 18:25 UTC by meta-nilesh-patel

2020-01-27 08:58 UTC, rash-tiwari commented on SCF/Session 6/Assignment6B/Poly.java
> +	Poly(int[] poly)throws IOException
Add space before ```throws```

2020-01-27 08:58 UTC, rash-tiwari commented on SCF/Session 6/Assignment6B/Poly.java
> +			throw new IOException("Null Polynomial Not Allowed");
Replace all ```IOException``` with either AssertionError or Exception

2020-01-27 09:00 UTC, rash-tiwari commented on SCF/Session 6/Assignment6B/Poly.java
> +final class Poly
Add ```public``` aceess specifier before class

2020-01-27 09:02 UTC, rash-tiwari commented on SCF/Session 6/Assignment6B/Poly.java
> +			for(int indexSecond = poly2.polynomial.length - 1;indexSecond >= 0; indexSecond--)
Add space after each operator

2020-01-27 09:07 UTC, rash-tiwari commented on SCF/Session 6/Assignment6B/TestAddPolyMethod.java
>  		catch(IOException io)
Add ```Exception``` in place of ```Exception```

2020-01-27 09:09 UTC, rash-tiwari requested changes
Code Review Done at 1st level

2020-01-27 09:36 UTC, meta-nilesh-patel commented on SCF/Session 6/Assignment6B/Poly.java
> +	Poly(int[] poly)throws IOException
Done

2020-01-27 09:36 UTC, meta-nilesh-patel commented on SCF/Session 6/Assignment6B/Poly.java
> +			throw new IOException("Null Polynomial Not Allowed");
Done

2020-01-27 09:36 UTC, meta-nilesh-patel commented on SCF/Session 6/Assignment6B/Poly.java
> +final class Poly
Done

2020-01-27 09:37 UTC, meta-nilesh-patel commented on SCF/Session 6/Assignment6B/Poly.java
> +			for(int indexSecond = poly2.polynomial.length - 1;indexSecond >= 0; indexSecond--)
Done

2020-01-27 09:37 UTC, meta-nilesh-patel commented on SCF/Session 6/Assignment6B/TestAddPolyMethod.java
>  		catch(IOException io)
Done

2020-01-27 09:38 UTC, meta-nilesh-patel reviewed
Done

2020-02-13 09:36 UTC, rash-tiwari approved these changes

2020-02-13 09:36 UTC, merged